name: rg
version: 0.7.1
summary: a line-oriented search tool that recursively searches for a regex pattern
grade: stable
description: |
  ripgrep is a line-oriented search tool that recursively searches
  your current directory for a regex pattern while respecting your
  gitignore rules. To a first approximation, ripgrep combines the
  usability of The Silver Searcher (similar to ack) with the raw
  speed of GNU grep. 
confinement: strict
apps:
  rg:
    command: rg
    plugs: [home]
parts:
  rg:
    plugin: rust
    source: https://github.com/BurntSushi/ripgrep.git
    source-tag: 0.7.1
